"use client";
/**
 * page.tsx
 * MOTOR TRANSFORMADOR — Single-file engine
 *
 * Objetivo:
 * - Transformar uma frase em código para muitos perfis / linguagens / países (template-driven).
 * - Sistema de Planos de Revenda (Grátis / Pro / Soberano) e Usuários Ilimitados.
 * - Usar apenas ferramentas gratuitas na camada de orientação (Supabase/Vercel opcionais — requires your keys).
 * - Botões de download reais e envio via WhatsApp (abre conversa pre-preenchida).
 *
 * Instruções:
 * - Cole em app/page.tsx de um projeto Next.js 13+ (App Router) ou use como componente React.
 * - Arquivo self-contained; persiste em localStorage (chave: plus_absurdo_v2).
 * - Para salvar em Supabase: configure SUPABASE_URL e SUPABASE_KEY nas Preferências (aba Export/Import).
 *
 * Nota de segurança:
 * - Este é um protótipo client-side. Integrações server-side, deploy automatizado ou pagamentos reais exigem chaves e infra que você pode configurar separadamente.
 */

import React, { useEffect, useMemo, useState } from "react";

/* ===========================
   Types & Constants
   =========================== */

type PlanSlug = "free" | "pro" | "soberano";
type Role = "owner" | "admin" | "editor" | "viewer";

type User = {
  id: string;
  name: string;
  email?: string;
  role: Role;
  color?: string;
};

type ProjectFile = {
  path: string;
  content: string;
  hint?: string;
};

type Project = {
  id: string;
  name: string;
  phrase: string; // user phrase used to generate
  profession: string;
  language: string;
  country?: string;
  files: ProjectFile[];
  createdAt: string;
  updatedAt: string;
};

type Ecosystem = {
  plan: PlanSlug;
  resellerName?: string;
  users: User[];
  projects: Project[];
  settings: {
    supabaseUrl?: string;
    supabaseKey?: string;
  };
  createdAt: string;
  updatedAt: string;
};

const STORAGE_KEY = "plus_absurdo_v2";

/* ===========================
   Helpers
   =========================== */

const uid = (prefix = "") =>
  prefix + Math.random().toString(36).slice(2, 9) + "-" + Date.now().toString(36).slice(-4);
const nowISO = () => new Date().toISOString();
const randomColor = () => ["#7c3aed", "#06b6d4", "#ef4444", "#f59e0b", "#10b981"][Math.floor(Math.random() * 5)];

const PLANS: Record<
  PlanSlug,
  { name: string; priceMonthlyUSD: number; features: string[]; resellerPct: number; unlimitedUsers: boolean }
> = {
  free: { name: "Grátis", priceMonthlyUSD: 0, features: ["Subdomínio público", "Templates básicos"], resellerPct: 0, unlimitedUsers: true },
  pro: { name: "Pro", priceMonthlyUSD: 29, features: ["Domínio custom", "Templates avançados", "API"], resellerPct: 10, unlimitedUsers: true },
  soberano: { name: "Soberano", priceMonthlyUSD: 199, features: ["Instância dedicada", "White-label", "SLA"], resellerPct: 30, unlimitedUsers: true },
};

/* ===========================
   Persistence
   =========================== */

const makeInitial = (): Ecosystem => {
  const owner: User = { id: uid("u-"), name: "Fundadora PLUS", email: "founder@plus.local", role: "owner", color: randomColor() };
  const seedProj: Project = {
    id: uid("pr-"),
    name: "Demo - Motor",
    phrase: "Crie uma landing pra consultório odontológico com agenda online",
    profession: "Dentist",
    language: "react",
    country: "BR",
    files: generateFromPhraseInternal("Crie uma landing pra consultório odontológico com agenda online", "Dentist", "react", "BR"),
    createdAt: nowISO(),
    updatedAt: nowISO(),
  };
  return {
    plan: "free",
    resellerName: "GRUPO PLUS",
    users: [owner],
    projects: [seedProj],
    settings: {},
    createdAt: nowISO(),
    updatedAt: nowISO(),
  };
};

const saveEco = (eco: Ecosystem) => {
  eco.updatedAt = nowISO();
  localStorage.setItem(STORAGE_KEY, JSON.stringify(eco));
};

const loadEco = (): Ecosystem => {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) {
    const seed = makeInitial();
    saveEco(seed);
    return seed;
  }
  try {
    const parsed = JSON.parse(raw) as Ecosystem;
    if (!parsed.users) parsed.users = makeInitial().users;
    if (!parsed.projects) parsed.projects = [];
    return parsed;
  } catch {
    const seed = makeInitial();
    saveEco(seed);
    return seed;
  }
};

/* ===========================
   Code Generator
   =========================== */

/**
 * generateFromPhraseInternal
 * - Rule-based generator: uses the user's phrase, profession, language and country to produce starter files.
 * - Expandable: add more languages and templates below.
 *
 * Note: Without an LLM, this generator uses templates + phrase injection to create meaningful starters for many stacks.
 */
function generateFromPhraseInternal(phrase: string, profession: string, language: string, country?: string): ProjectFile[] {
  const prof = profession || "Professional";
  const lang = (language || "html").toLowerCase();
  const ctxComment = `/* Generated by MOTOR ABSURDO — phrase: "${phrase.replace(/\n/g, " ")}" — profession: ${prof} — country: ${country || "global"} */\n\n`;

  const templates: Record<string, () => ProjectFile[]> = {
    html: () => [
      {
        path: "index.html",
        content:
          ctxComment +
          `<!doctype html>\n<html lang="${country === "BR" ? "pt-BR" : "en"}">\n<head>\n  <meta charset="utf-8"/>\n  <meta name="viewport" content="width=device-width,initial-scale=1"/>\n  <title>${prof} — Landing</title>\n</head>\n<body>\n  <main>\n    <h1>${prof} — Landing</h1>\n    <p>${phrase}</p>\n  </main>\n</body>\n</html>`,
        hint: "html",
      },
    ],
    react: () => [
      {
        path: "src/App.jsx",
        content:
          ctxComment +
          `import React from "react";\nexport default function App(){\n  return (\n    <div style={{fontFamily:"Inter,system-ui",padding:20}}>\n      <header><h1>${prof} — Landing</h1></header>\n      <p>${phrase}</p>\n      <section>\n        <h2>Call to Action</h2>\n        <button style={{background:"#7c3aed",color:"#fff",padding:"8px 12px",borderRadius:8}}>Agendar</button>\n      </section>\n    </div>\n  );\n}\n`,
        hint: "jsx",
      },
      {
        path: "package.json",
        content: JSON.stringify({ name: prof.toLowerCase().replace(/\s+/g, "-"), private: true, dependencies: { react: "^18.2.0" } }, null, 2),
      },
    ],
    next: () => [
      {
        path: "app/page.tsx",
        content:
          ctxComment +
          `import React from "react";\nexport default function Page(){\n  return (\n    <main style={{padding:24,fontFamily:"Inter,system-ui"}}>\n      <h1>${prof} — Next.js</h1>\n      <p>${phrase}</p>\n    </main>\n  );\n}\n`,
        hint: "tsx",
      },
    ],
    node: () => [
      {
        path: "index.js",
        content:
          ctxComment +
          "const express = require('express');\nconst app = express();\napp.get('/', (req,res) => res.send(`<h1>" + prof + "</h1><p>" + phrase.replace(/`/g, "'") + "</p>`));\napp.listen(3000,()=>console.log('Listening 3000'));\n",
      },
      { path: "package.json", content: JSON.stringify({ name: prof, dependencies: { express: "^4.18.2" } }, null, 2) },
    ],
    flask: () => [
      {
        path: "app.py",
        content:
          ctxComment +
          `from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef home():\n    return '<h1>${prof}</h1><p>${phrase.replace(/'/g, "\\'")}</p>'\n\nif __name__=='__main__':\n    app.run(debug=True)\n`,
      },
      { path: "requirements.txt", content: "flask\n" },
    ],
    go: () => [
      {
        path: "main.go",
        content:
          ctxComment +
          `package main\nimport (\n  "fmt"\n  "net/http"\n)\nfunc handler(w http.ResponseWriter, r *http.Request){fmt.Fprint(w,"<h1>${prof}</h1><p>${phrase.replace(/\"/g, "'")}</p>")}\nfunc main(){http.HandleFunc("/",handler);http.ListenAndServe(":8080",nil)}\n`,
      },
    ],
    flutter: () => [
      {
        path: "lib/main.dart",
        content:
          ctxComment + `import 'package:flutter/material.dart';\nvoid main()=>runApp(MaterialApp(home: Scaffold(body: Center(child: Text('${prof}')))));\n`,
      },
    ],
    php: () => [
      {
        path: "index.php",
        content: ctxComment + `<?php echo '<h1>${prof}</h1><p>${phrase}</p>'; ?>`,
      },
    ],
    default: () => [
      { path: "README.md", content: ctxComment + `# ${prof}\n\nPhrase: ${phrase}\n\nGenerated generic scaffold.` },
    ],
  };

  const key = lang in templates ? lang : "default";
  return templates[key]() as ProjectFile[];
}

/* expose generator for UI usage */
function generateFromPhrase(phrase: string, profession: string, language: string, country?: string) {
  return generateFromPhraseInternal(phrase, profession, language, country);
}

/* ===========================
   UI Component
   =========================== */

export default function Page() {
  const [eco, setEco] = useState<Ecosystem | null>(null);
  const [tab, setTab] = useState<"generator" | "projects" | "users" | "billing" | "export">("generator");
  const [langUI, setLangUI] = useState<"pt" | "en">("pt");

  useEffect(() => {
    const loaded = loadEco();
    setEco(loaded);
  }, []);

  useEffect(() => {
    if (eco) saveEco(eco);
  }, [eco]);

  if (!eco) return <div style={styles.container}>Carregando...</div>;

  /* --- Users management --- */
  const addUser = (name: string, email?: string, role: Role = "editor") => {
    const user: User = { id: uid("u-"), name, email, role, color: randomColor() };
    setEco((p) => (p ? { ...p, users: [user, ...p.users] } : p));
  };
  const updateUserRole = (id: string, role: Role) => {
    setEco((p) => (p ? { ...p, users: p.users.map((u) => (u.id === id ? { ...u, role } : u)) } : p));
  };
  const removeUser = (id: string) => {
    if (!confirm("Remover usuário?")) return;
    setEco((p) => (p ? { ...p, users: p.users.filter((u) => u.id !== id) } : p));
  };

  /* --- Projects management --- */
  const createProject = (name: string, phrase: string, profession: string, language: string, country?: string) => {
    const files = generateFromPhrase(phrase, profession, language, country);
    const prj: Project = { id: uid("pr-"), name, phrase, profession, language, country, files, createdAt: nowISO(), updatedAt: nowISO() };
    setEco((p) => (p ? { ...p, projects: [prj, ...p.projects] } : p));
    return prj;
  };

  const deleteProject = (id: string) => {
    if (!confirm("Remover projeto?")) return;
    setEco((p) => (p ? { ...p, projects: p.projects.filter((pr) => pr.id !== id) } : p));
  };

  const downloadFile = (file: ProjectFile) => {
    const blob = new Blob([file.content], { type: "text/plain;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = file.path.split("/").pop() || "file.txt";
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const downloadProjectBundle = (project: Project) => {
    // Make a textual bundle (simple and reliable without external libs).
    const bundle = project.files.map((f) => `--- ${f.path} ---\n${f.content}`).join("\n\n");
    const blob = new Blob([bundle], { type: "text/plain;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${project.name.replace(/\s+/g, "_")}_bundle.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const shareViaWhatsApp = (text: string) => {
    const payload = encodeURIComponent(text.slice(0, 1900));
    const url = `https://wa.me/?text=${payload}`;
    window.open(url, "_blank");
  };

  const exportJSON = () => {
    const blob = new Blob([JSON.stringify(eco, null, 2)], { type: "application/json" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `plus_absurdo_export_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const importJSON = (raw: string) => {
    try {
      const parsed = JSON.parse(raw) as Ecosystem;
      if (!parsed) throw new Error("Invalid JSON");
      setEco({ ...parsed, updatedAt: nowISO() });
      alert("Importado com sucesso.");
    } catch (e: any) {
      alert("Erro ao importar: " + e.message);
    }
  };

  const saveProjectToSupabase = async (project: Project) => {
    if (!eco.settings.supabaseUrl || !eco.settings.supabaseKey) {
      alert("Configure SUPABASE_URL e SUPABASE_KEY nas Preferências (Export/Import).");
      return;
    }
    try {
      const url = `${eco.settings.supabaseUrl.replace(/\/$/, "")}/rest/v1/plus_projects`;
      const body = {
        id: project.id,
        name: project.name,
        phrase: project.phrase,
        profession: project.profession,
        language: project.language,
        country: project.country,
        files: JSON.stringify(project.files),
        created_at: project.createdAt,
      };
      const res = await fetch(url, {
        method: "POST",
        headers: {
          apikey: eco.settings.supabaseKey!,
          Authorization: `Bearer ${eco.settings.supabaseKey!}`,
          "Content-Type": "application/json",
          Prefer: "return=representation",
        },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const txt = await res.text();
        throw new Error(`${res.status} ${txt}`);
      }
      alert("Projeto salvo no Supabase. Verifique a tabela plus_projects.");
    } catch (e: any) {
      alert("Erro Supabase: " + e.message);
    }
  };

  /* ===========================
     Render
     =========================== */

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
          <div style={styles.logo}>+</div>
          <div>
            <div style={{ fontWeight: 900, fontSize: 18 }}>MOTOR TRANSFORMADOR — GRUPO PLUS</div>
            <div style={{ fontSize: 12, color: "#666" }}>Transforme uma frase em código (protótipo)</div>
          </div>
          <div style={{ marginLeft: 12 }}>
            <span style={styles.badge}>{PLANS[eco.plan].name}</span>
          </div>
        </div>

        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          <select value={langUI} onChange={(e) => setLangUI(e.target.value as any)} style={styles.select}>
            <option value="pt">PT</option>
            <option value="en">EN</option>
          </select>

          <select value={tab} onChange={(e) => setTab(e.target.value as any)} style={styles.select}>
            <option value="generator">{langUI === "pt" ? "Gerador" : "Generator"}</option>
            <option value="projects">{langUI === "pt" ? "Projetos" : "Projects"}</option>
            <option value="users">{langUI === "pt" ? "Usuários" : "Users"}</option>
            <option value="billing">{langUI === "pt" ? "Faturamento" : "Billing"}</option>
            <option value="export">{langUI === "pt" ? "Export/Import" : "Export/Import"}</option>
          </select>

          <div style={{ fontSize: 13, color: "#444" }}>
            {langUI === "pt" ? "Usuários:" : "Users:"} <strong>{eco.users.length}</strong>
          </div>
        </div>
      </header>

      <main style={styles.main}>
        {tab === "generator" && (
          <section style={styles.card}>
            <h2 style={{ marginTop: 0 }}>{langUI === "pt" ? "Transforme frase em código" : "Phrase → Code"}</h2>
            <GeneratorPanel
              onCreate={(name, phrase, profession, language, country) => {
                const prj = createProject(name, phrase, profession, language, country);
                alert(`${langUI === "pt" ? "Projeto criado" : "Project created"}: ${prj.name}`);
                setTab("projects");
              }}
            />
          </section>
        )}

        {tab === "projects" && (
          <section style={styles.card}>
            <h2 style={{ marginTop: 0 }}>{langUI === "pt" ? "Projetos gerados" : "Generated Projects"}</h2>
            <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
              {eco.projects.map((p) => (
                <div key={p.id} style={styles.projectCard}>
                  <div>
                    <div style={{ fontWeight: 800 }}>{p.name}</div>
                    <div style={{ fontSize: 12, color: "#666" }}>{p.profession} • {p.language} • {new Date(p.updatedAt).toLocaleString()}</div>
                  </div>
                  <div style={{ display: "flex", gap: 8 }}>
                    <button style={styles.button} onClick={() => {
                      const sample = p.files.map(f => `--- ${f.path} ---\n${f.content.slice(0, 800)}${f.content.length > 800 ? "\n\n... (truncated)" : ""}`).join("\n\n");
                      alert(sample);
                    }}>{langUI === "pt" ? "Visualizar" : "Preview"}</button>

                    <button style={styles.buttonAlt} onClick={() => downloadProjectBundle(p)}>{langUI === "pt" ? "Download Bundle" : "Download Bundle"}</button>

                    <button style={styles.buttonAlt} onClick={() => {
                      const txt = p.files.map(f => `File: ${f.path}\n\n${f.content}`).join("\n\n");
                      shareViaWhatsApp(`Projeto: ${p.name}\n\n${txt.slice(0, 1700)}`);
                    }}>{langUI === "pt" ? "Enviar via WhatsApp" : "Share via WhatsApp"}</button>

                    <button style={styles.buttonAlt} onClick={() => saveProjectToSupabase(p)}>{langUI === "pt" ? "Salvar no Supabase" : "Save to Supabase"}</button>

                    <button style={styles.buttonDanger} onClick={() => deleteProject(p.id)}>{langUI === "pt" ? "Remover" : "Delete"}</button>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {tab === "users" && (
          <section style={styles.card}>
            <h2 style={{ marginTop: 0 }}>{langUI === "pt" ? "Usuários" : "Users"}</h2>
            <UserManager eco={eco} onAdd={addUser} onUpdateRole={updateUserRole} onRemove={removeUser} />
          </section>
        )}

        {tab === "billing" && (
          <section style={styles.card}>
            <h2 style={{ marginTop: 0 }}>{langUI === "pt" ? "Planos e Revenda" : "Plans & Reseller"}</h2>
            <div style={{ display: "flex", gap: 12 }}>
              {Object.keys(PLANS).map((k) => {
                const slug = k as PlanSlug;
                const p = PLANS[slug];
                return (
                  <div key={slug} style={{ border: eco.plan === slug ? "2px solid #7c3aed" : "1px solid #eee", padding: 12, borderRadius: 8, width: 220 }}>
                    <div style={{ fontWeight: 800 }}>{p.name}</div>
                    <div style={{ fontSize: 12, color: "#666" }}>${p.priceMonthlyUSD}/m</div>
                    <div style={{ marginTop: 8 }}>
                      {p.features.map((f) => <div key={f} style={{ fontSize: 13 }}>{f}</div>)}
                    </div>
                    <div style={{ marginTop: 8 }}>
                      <button style={styles.buttonAlt} onClick={() => setEco({ ...eco, plan: slug })}>{langUI === "pt" ? "Ativar" : "Activate"}</button>
                    </div>
                    <div style={{ marginTop: 8, fontSize: 12, color: "#666" }}>
                      Reseller: {p.resellerPct}%
                    </div>
                  </div>
                );
              })}
            </div>

            <div style={{ marginTop: 12 }}>
              <strong>{langUI === "pt" ? "Usuários Ilimitados" : "Unlimited Users"}</strong> — todos os planos neste protótipo permitem criação ilimitada de usuários conforme solicitado.
            </div>
          </section>
        )}

        {tab === "export" && (
          <section style={styles.card}>
            <h2 style={{ marginTop: 0 }}>{langUI === "pt" ? "Export / Import & Supabase" : "Export / Import & Supabase"}</h2>
            <div style={{ display: "flex", gap: 12 }}>
              <div style={{ flex: 1 }}>
                <div style={{ display: "flex", gap: 8, marginBottom: 8 }}>
                  <button style={styles.button} onClick={() => exportJSON()}>{langUI === "pt" ? "Exportar JSON" : "Export JSON"}</button>
                  <button style={styles.buttonAlt} onClick={() => navigator.clipboard?.writeText(JSON.stringify(eco)).then(()=>alert(langUI === "pt" ? "JSON copiado" : "JSON copied"))}>{langUI === "pt" ? "Copiar JSON" : "Copy JSON"}</button>
                </div>

                <div style={{ marginTop: 12 }}>
                  <h4>{langUI === "pt" ? "Configurar Supabase (opcional)" : "Supabase Settings (optional)"}</h4>
                  <input placeholder="SUPABASE_URL" style={styles.input} value={eco.settings.supabaseUrl || ""} onChange={(e) => setEco({ ...eco, settings: { ...eco.settings, supabaseUrl: e.target.value } })} />
                  <input placeholder="SUPABASE_KEY (anon)" style={styles.input} value={eco.settings.supabaseKey || ""} onChange={(e) => setEco({ ...eco, settings: { ...eco.settings, supabaseKey: e.target.value } })} />
                  <div style={{ fontSize: 12, color: "#666", marginTop: 8 }}>
                    Dica: crie tabela 'plus_projects' com colunas id, name, phrase, profession, language, country, files (jsonb/text), created_at.
                  </div>
                </div>
              </div>

              <aside style={{ width: 420 }}>
                <h4>{langUI === "pt" ? "Importar JSON" : "Import JSON"}</h4>
                <textarea id="importArea" style={{ width: "100%", height: 220 }} placeholder={langUI === "pt" ? "Cole JSON aqui..." : "Paste JSON here..."} />
                <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
                  <button style={styles.buttonAlt} onClick={() => {
                    const el = document.getElementById("importArea") as HTMLTextAreaElement | null;
                    if (!el || !el.value) return alert(langUI === "pt" ? "Cole o JSON" : "Paste JSON");
                    if (!confirm(langUI === "pt" ? "Importar substituirá os dados atuais. Prosseguir?" : "Import will replace current state. Proceed?")) return;
                    importJSON(el.value);
                  }}>{langUI === "pt" ? "Importar" : "Import"}</button>

                  <button style={styles.button} onClick={() => {
                    const el = document.getElementById("importArea") as HTMLTextAreaElement | null;
                    if (el) el.value = JSON.stringify(eco, null, 2);
                  }}>{langUI === "pt" ? "Preencher com estado atual" : "Fill with current state"}</button>
                </div>
              </aside>
            </div>
          </section>
        )}
      </main>

      <footer style={styles.footer}>
        <div>GRUPO PLUS • {new Date().getFullYear()} • Protótipo sem cascas</div>
        <div style={{ color: "#666", fontSize: 12 }}>
          {langUI === "pt" ? "Para deploy real (Vercel/Supabase) forneça chaves e crie a tabela recomendada." : "For real deploy (Vercel/Supabase) provide keys and create the recommended table."}
        </div>
      </footer>
    </div>
  );
}

/* ===========================
   Subcomponents
   =========================== */

function GeneratorPanel({ onCreate }: { onCreate: (name: string, phrase: string, profession: string, language: string, country?: string) => void }) {
  const [name, setName] = useState("");
  const [phrase, setPhrase] = useState("");
  const [profession, setProfession] = useState("Photographer");
  const [language, setLanguage] = useState("react");
  const [country, setCountry] = useState("");

  return (
    <div style={{ display: "flex", gap: 8, flexDirection: "column" }}>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
        <input placeholder="Nome do projeto" value={name} onChange={(e) => setName(e.target.value)} style={styles.input} />
        <select value={profession} onChange={(e) => setProfession(e.target.value)} style={styles.select}>
          <option>Photographer</option>
          <option>Restaurant</option>
          <option>Doctor</option>
          <option>Dentist</option>
          <option>Lawyer</option>
          <option>Teacher</option>
          <option>Developer</option>
          <option>Agency</option>
          <option>eCommerce</option>
        </select>
        <select value={language} onChange={(e) => setLanguage(e.target.value)} style={styles.select}>
          <option value="react">React</option>
          <option value="next">Next.js</option>
          <option value="html">HTML</option>
          <option value="flask">Flask</option>
          <option value="node">Node/Express</option>
          <option value="go">Go</option>
          <option value="flutter">Flutter</option>
          <option value="php">PHP</option>
        </select>
        <input placeholder="Country (BR, US, IN...)" value={country} onChange={(e) => setCountry(e.target.value)} style={styles.inputSmall} />
      </div>

      <textarea placeholder="Descreva em uma frase o que quer (ex: 'Landing para clínica com agendamento online e formulário de contato')" value={phrase} onChange={(e) => setPhrase(e.target.value)} style={{ width: "100%", height: 120, padding: 8, borderRadius: 8, border: "1px solid #ddd" }} />

      <div style={{ display: "flex", gap: 8 }}>
        <button style={styles.button} onClick={() => {
          if (!name) return alert("Informe um nome para o projeto.");
          if (!phrase) return alert("Forneça a frase/descritivo.");
          onCreate(name, phrase, profession, language, country || undefined);
        }}>Gerar e Criar</button>

        <button style={styles.buttonAlt} onClick={() => {
          // Preview generation without creating
          if (!phrase) return alert("Forneça a frase/descritivo.");
          const files = generateFromPhrase(phrase, profession, language, country || undefined);
          const preview = files.map(f => `--- ${f.path} ---\n${f.content.slice(0, 1200)}${f.content.length > 1200 ? "\n\n... (truncated)" : ""}`).join("\n\n");
          alert(preview);
        }}>Visualizar</button>
      </div>

      <div style={{ fontSize: 12, color: "#666" }}>
        Dica: Frases curtas e objetivas produzem melhores scaffolds. Para deploy real, conecte a Supabase e crie tabela 'plus_projects'.
      </div>
    </div>
  );
}

function UserManager({ eco, onAdd, onUpdateRole, onRemove }: { eco: Ecosystem; onAdd: (name: string, email?: string, role?: Role) => void; onUpdateRole: (id: string, role: Role) => void; onRemove: (id: string) => void }) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<Role>("editor");

  return (
    <div style={{ display: "flex", gap: 12 }}>
      <div style={{ flex: 1 }}>
        <div style={{ display: "flex", gap: 8 }}>
          <input placeholder="Nome" value={name} onChange={(e) => setName(e.target.value)} style={styles.input} />
          <input placeholder="Email (opcional)" value={email} onChange={(e) => setEmail(e.target.value)} style={styles.input} />
          <select value={role} onChange={(e) => setRole(e.target.value as Role)} style={styles.select}>
            <option value="owner">owner</option>
            <option value="admin">admin</option>
            <option value="editor">editor</option>
            <option value="viewer">viewer</option>
          </select>
          <button style={styles.button} onClick={() => { if (!name) return alert("Nome obrigatório"); onAdd(name, email || undefined, role); setName(""); setEmail(""); }}>Criar</button>
        </div>

        <div style={{ marginTop: 12 }}>
          {eco.users.map(u => (
            <div key={u.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: 10, borderRadius: 8, background: "#fff", marginBottom: 8 }}>
              <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
                <div style={{ width: 40, height: 40, borderRadius: 8, background: u.color || "#ddd", color: "#fff", fontWeight: 900, display: "flex", alignItems: "center", justifyContent: "center" }}>{u.name[0]}</div>
                <div>
                  <div style={{ fontWeight: 700 }}>{u.name}</div>
                  <div style={{ fontSize: 12, color: "#666" }}>{u.email || "—"} • {u.role}</div>
                </div>
              </div>

              <div style={{ display: "flex", gap: 8 }}>
                <select value={u.role} onChange={(e) => onUpdateRole(u.id, e.target.value as Role)} style={styles.select}>
                  <option value="owner">owner</option>
                  <option value="admin">admin</option>
                  <option value="editor">editor</option>
                  <option value="viewer">viewer</option>
                </select>
                <button style={styles.buttonDanger} onClick={() => onRemove(u.id)}>Remover</button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <aside style={{ width: 320 }}>
        <div style={{ background: "#fff", padding: 12, borderRadius: 8 }}>
          <h4>Usuários Ilimitados</h4>
          <p style={{ fontSize: 13 }}>Todos os planos permitem criação ilimitada de usuários — esse é o comportamento do motor sem restrições.</p>
        </div>
      </aside>
    </div>
  );
}

/* ===========================
   Styles
   =========================== */

const styles: Record<string, React.CSSProperties> = {
  container: { padding: 18, fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Arial", background: "#f5f7fb", minHeight: "100vh", color: "#111" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 },
  logo: { width: 48, height: 48, borderRadius: 10, background: "#7c3aed", color: "#fff", fontWeight: 900, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22 },
  badge: { padding: "4px 8px", borderRadius: 8, background: "#ecfeff", color: "#0ea5a4", fontWeight: 700 },
  select: { padding: "8px 10px", borderRadius: 8, border: "1px solid #ddd", background: "#fff" },
  input: { padding: "8px 10px", borderRadius: 8, border: "1px solid #ddd", width: 240 },
  inputSmall: { padding: "8px 10px", borderRadius: 8, border: "1px solid #ddd", width: 120 },
  button: { padding: "8px 12px", borderRadius: 8, background: "#7c3aed", color: "#fff", border: "none", cursor: "pointer" },
  buttonAlt: { padding: "8px 12px", borderRadius: 8, background: "#fff", color: "#111", border: "1px solid #ddd", cursor: "pointer" },
  buttonDanger: { padding: "8px 12px", borderRadius: 8, background: "#ef4444", color: "#fff", border: "none", cursor: "pointer" },
  main: { display: "block" },
  card: { background: "#fff", borderRadius: 12, padding: 16, boxShadow: "0 2px 8px rgba(2,6,23,0.04)", marginBottom: 12 },
  projectCard: { background: "#fff", borderRadius: 10, padding: 12, minWidth: 320, display: "flex", justifyContent: "space-between", alignItems: "center", boxShadow: "0 1px 3px rgba(0,0,0,0.04)" },
  footer: { marginTop: 24, color: "#666", display: "flex", justifyContent: "space-between", fontSize: 13 },
};

/* ===========================
   End of file
   =========================== */
